site_name: Les meues práctiques

nav:
 - Inici: index.md
 - Pràctica 1: practica1.md
 - Pràctica 2: practica2.md
 - Práctica 3: practica3.md
 - Pràctica 4: practica4.md
 - Pràctica 5: practica5.md
theme:
  name: material
  palette:
    # Mode clar (per defecte)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    # Mode fosc automàtic
    - media: "(prefers-color-scheme: dark)"
      schema: slate
      primary: indigo
      accent: indigo
